#include <nuttx/compiler.h>
#include <nuttx/binfmt/symtab.h>

extern void *__aeabi_atexit;
EXPORT_SYMBOL(__aeabi_atexit);
extern void *__dso_handle;
EXPORT_SYMBOL(__dso_handle);
extern void *exit;
EXPORT_SYMBOL(exit);
extern void *fflush;
EXPORT_SYMBOL(fflush);
extern void *fopen;
EXPORT_SYMBOL(fopen);
extern void *fprintf;
EXPORT_SYMBOL(fprintf);
extern void *get_errno_ptr;
EXPORT_SYMBOL(get_errno_ptr);
extern void *getpid;
EXPORT_SYMBOL(getpid);
extern void *kill;
EXPORT_SYMBOL(kill);
extern void *memset;
EXPORT_SYMBOL(memset);
extern void *printf;
EXPORT_SYMBOL(printf);
extern void *pthread_attr_init;
EXPORT_SYMBOL(pthread_attr_init);
extern void *pthread_create;
EXPORT_SYMBOL(pthread_create);
extern void *pthread_exit;
EXPORT_SYMBOL(pthread_exit);
extern void *pthread_join;
EXPORT_SYMBOL(pthread_join);
extern void *pthread_mutex_init;
EXPORT_SYMBOL(pthread_mutex_init);
extern void *pthread_mutex_lock;
EXPORT_SYMBOL(pthread_mutex_lock);
extern void *pthread_mutex_unlock;
EXPORT_SYMBOL(pthread_mutex_unlock);
extern void *puts;
EXPORT_SYMBOL(puts);
extern void *sched_getstreams;
EXPORT_SYMBOL(sched_getstreams);
extern void *sem_destroy;
EXPORT_SYMBOL(sem_destroy);
extern void *sem_init;
EXPORT_SYMBOL(sem_init);
extern void *sem_post;
EXPORT_SYMBOL(sem_post);
extern void *sem_wait;
EXPORT_SYMBOL(sem_wait);
extern void *sigaction;
EXPORT_SYMBOL(sigaction);
extern void *sigemptyset;
EXPORT_SYMBOL(sigemptyset);
extern void *sigqueue;
EXPORT_SYMBOL(sigqueue);
extern void *sleep;
EXPORT_SYMBOL(sleep);
extern void *strcmp;
EXPORT_SYMBOL(strcmp);
extern void *task_create;
EXPORT_SYMBOL(task_create);
extern void *usleep;
EXPORT_SYMBOL(usleep);
extern void *_ZdlPv;
EXPORT_SYMBOL(_ZdlPv);
extern void *_Znwj;
EXPORT_SYMBOL(_Znwj);
extern void *_ZTVN10__cxxabiv117__class_type_infoE;
EXPORT_SYMBOL(_ZTVN10__cxxabiv117__class_type_infoE);

